FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc gfortran g++ libblas-dev libhdf5-dev liblapack-dev libopenblas-dev python3-dev \
    && rm -rf /var/lib/apt/lists/*

COPY vasq/requirements.txt /app/requirements.txt
RUN pip install --upgrade pip && pip install -r /app/requirements.txt gunicorn
RUN which gunicorn && gunicorn --version

COPY vasq/ /app/
COPY vasq/data/ /data/

RUN python manage.py collectstatic --noinput

CMD ["bash", "-lc", "gunicorn newui.wsgi:application --bind 0.0.0.0:${PORT:-8000} --workers 1 --timeout 300"]
#CMD ["bash", "-lc", "gunicorn newui.wsgi:application --bind 0.0.0.0:${PORT:-8000} --workers 2 --timeout 120"]
